version: '3.0'
services:
  llm_server:
    container_name: llm_server
    image: llm_server:1.0
    working_dir: /work
    gpus: all
    volumes:
      - ./:/work
    ports:
      - 8888:8888
    stdin_open: true
    tty: true